name       : cmus
version    : 2.7.0
release    : 3
source     :
    - https://github.com/cmus/cmus/archive/v2.7.0.tar.gz : ad4bbc6828f162d56f7f2d61e60714df8f1006a2000cc7e2b867ba93352997e9
license    : GPL-2.0
component  : multimedia.audio
summary    : Small, fast and powerful console music player for Unix-like operating
    systems
description: |
    Small, fast and powerful console music player for Unix-like operating systems
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(ao)
    - pkgconfig(flac)
    - pkgconfig(jack)
    - pkgconfig(libavformat)
    - pkgconfig(libcddb)
    - pkgconfig(libcdio)
    - pkgconfig(libcue)
    - pkgconfig(libmodplug)
    - pkgconfig(libpulse)
    - pkgconfig(opusfile)
    - pkgconfig(samplerate)
    - pkgconfig(vorbis)
    - pkgconfig(wavpack)
    - faad-devel
    - libmad-devel
setup      : |
    ./configure prefix=/usr libdir=/usr/lib64
build      : |
    %make
install    : |
    %make_install
