name       : cmus
version    : 2.8.0_rc0
release    : 8
source     :
    - git|https://github.com/cmus/cmus.git : b382e6f951b99002cb6e614a4797892e12afcfd8
license    : GPL-2.0
component  : multimedia.audio
summary    : Small, fast and powerful console music player for Unix-like operating systems
description: |
    Small, fast and powerful console music player for Unix-like operating systems
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(ao)
    - pkgconfig(flac)
    - pkgconfig(libavformat)
    - pkgconfig(libcddb)
    - pkgconfig(libcdio)
    - pkgconfig(libcue)
    - pkgconfig(libmodplug)
    - pkgconfig(libpulse)
    - pkgconfig(opusfile)
    - pkgconfig(samplerate)
    - pkgconfig(vorbis)
    - pkgconfig(wavpack)
    - faad-devel
    - libmad-devel
setup      : |
    # We don't have sd-bus.h in solus *yet* until the systemd update is done
    ./configure prefix=/usr libdir=/usr/lib64 CONFIG_JACK=n CONFIG_MPRIS=n
build      : |
    %make
install    : |
    %make_install
